---
title: "Final COMP112 Group Project"
author: "RACHEL, NORA, EMANUEL"
date: "4/7/2022"
output: html_document
code_download: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r load-libraries}
library(ggplot2)
library(dplyr)
library(tidyverse)
library(readr)
library(sf) 
#library(showtext)

theme_set(theme_minimal())
```


```{r load-data}
solar_data <- read_csv("mnsolar5.csv")
```


```{r utility-installations}
installs_graph <- solar_data %>% 
  group_by(Utility) %>% 
  summarise(Utility_n = n()) %>%
  mutate(total_n = sum(Utility_n),
         percent_total = ((Utility_n/total_n)*100)) %>% 
  arrange(desc(percent_total)) %>% 
  ggplot() +
  geom_bar(
    mapping = aes(x = Utility, fill = percent_total),
    show.legend = FALSE,
    width = 1
  ) +
  theme(aspect.ratio = 1) +
  labs(x = NULL, y = NULL)

installs_graph + coord_polar()
```

```{r utility-capacity}
solar_data %>% 
  group_by(Utility) %>% 
  summarise(total_capacity = sum(`DER Capacity kW AC`)) %>% 
  mutate(overall_capacity = sum(total_capacity),
         percent_total = ((total_capacity/overall_capacity)*100)) %>% 
  arrange(desc(percent_total))
```


```{r cumulative-capacity}
solar_data %>% 
  group_by(`Year Interconnected`) %>% 
  filter(`Year Interconnected` != 2021) %>% 
  summarise(sum_capacity = sum(capacity_MW)) %>% 
  mutate(cum_sum_capacity = cumsum(sum_capacity)) %>% 
  ggplot(aes(x = `Year Interconnected`, y = cum_sum_capacity)) +
  geom_line() +
  labs(x = "", y = "", title = "Cumulative Solar Capacity - Statewide (MW)")
```


```{r installations-added}
solar_data %>%
  select(City, `Year Interconnected`, `Customer Type`) %>% 
  filter(`Year Interconnected` != 2021) %>% 
  filter(`Customer Type` != c("NA")) %>% 
  group_by(`Year Interconnected`, `Customer Type`) %>%
  summarise(installs_n = n()) %>% 
  ungroup() %>% 
  ggplot(aes(x = `Year Interconnected`, y = installs_n, color = `Customer Type`)) +
  geom_line() +
  labs(x = "", y = "", title = "Annual Solar Installation Growth by Customer Type - Statewide") 
```



```{r fig.width = 20, fig.height = 12, fig.alt="Proportion bar graph of Minnesota Solar Customer Types by Utilities"}
solar_data %>% 
  select(Utility, City, `Customer Type`) %>% 
  group_by(Utility, `Customer Type`) %>%
  summarise(total_type = n()) %>% 
  ggplot() + 
  geom_bar(mapping = aes(x = Utility, fill = `Customer Type`), position = "fill") +
  scale_y_continuous(expand=c(0,0)) +
  theme(axis.text.x = element_text(angle = 45,
                                   hjust = 0.95),
        plot.title = element_text(size = 20)) +
  labs(title = "Tidy Tuesday: Proportion of Minnesota Solar Customer Types by Utilities",
       caption = "Graph made by Rachel Percy | April 7, 2022 \nData from Public Utilities Commission",
       x = "",
       y = "")
```


